### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by ViniMoraes** [Lucas-lusca/CRUD-NET_CORE#1]
Could you add a `.gitignore` file?
It will help to remove some configurations of your IDE and keep your repo cleaner

if for example, I use same IDE as you, I would have conflicts with your configurations

some folders that wouldn't be necessary in repo:

`.vscode`
`/bin/...`

I would recommend you to get a `.gitignore` file already done instead of creating your own
some files you can use:
https://github.com/github/gitignore

**Comment by Lucas-lusca** [comment]
Hello my friend, thank you for your feedback, after picking up a bit for
git, I think I managed to fix the problem, when I can take a look again.

https://github.com/Lucas-lusca/UM-LUGAR/tree/Em-MVC

Em qua., 12 de out. de 2022 às 18:58, Vinicius H Moraes <
***@***.***> escreveu:

**Comment by Lucas-lusca** [comment]
Sorry my english, hehehehe

Em qua., 12 de out. de 2022 às 20:08, Lucas ***@***.***>
escreveu:

**Comment by ViniMoraes** [comment]
It looks awesome! much cleaner! 🚀
